### PR TITLE
Andy zheng430/integration test controllers

### PR DESCRIPTION
**Pull request by AndyZheng430**
### **Changes:**
[+] Modified integration tests to interact with PostgreSQL database for BucketController, BudgetController, MonthlySummaryController.
[+] Replaced @MockBean and @WebMvcTest with @SpringBootTest and @AutoConfigureMockMvc. 
[+] Added @Transactional to reset changes to database after each test method, however, it does not drop tables/reset database.
[+] Mocked TransactionService in BudgetControllerIntegrationTest because no instance in TransactionService could not be found. 
[+] Renamed TrancationService to TransactionService.
[+] Added FailSafe plugin to prevent integration testing to stop if one test fails. 
[+] Changed unit test and integration test folder structures

### CODE REVIEW

**Comment by AndyZheng430** [comment]
We are missing the coverage report for integration testing, but I do not think it is necessary to reach a certain level

**Review by brittshook — CHANGES_REQUESTED** [review]
- I am getting an llegalStateException: No instances available for transaction_service on BudgetControllerIntegrationTest.testGetTranscationsByMonthYear; you'll want to do a mock bean of transaction service and mock it like you did in transaction service unit testing 
- Transaction is misspelled across testing + dev files - I think we should go in and correct (it's spelled Transcation - with a & c swapped  - in many places)

**Comment by AndyZheng430** [comment]
> * I am getting an llegalStateException: No instances available for transaction_service on BudgetControllerIntegrationTest.testGetTranscationsByMonthYear; you'll want to do a mock bean of transaction service and mock it like you did in transaction service unit testing
> * Transaction is misspelled across testing + dev files - I think we should go in and correct (it's spelled Transcation - with a & c swapped  - in many places)

Both issues should be fixed. 
With full integration testing, we usually don't want to mock services or controllers, so we can verify the code works together. I had to mock the TransactionService in BudgetControllerIntegrationTest because of that error. It seems like the instances in TransactionService can't be found and is null.

**Review by bbvicente — APPROVED** [review]
Looks good! Thanks for making all the name changes

**Review by brittshook — APPROVED** [review]
Great work! Thank you!

**Comment by brittshook** [comment]
> > * I am getting an llegalStateException: No instances available for transaction_service on BudgetControllerIntegrationTest.testGetTranscationsByMonthYear; you'll want to do a mock bean of transaction service and mock it like you did in transaction service unit testing
> > * Transaction is misspelled across testing + dev files - I think we should go in and correct (it's spelled Transcation - with a & c swapped  - in many places)
> 
> Both issues should be fixed. With full integration testing, we usually don't want to mock services or controllers, so we can verify the code works together. I had to mock the TransactionService in BudgetControllerIntegrationTest because of that error. It seems like the instances in TransactionService can't be found and is null.

Agreed - we're not worried about doing full integration testing is my understanding from Caroline. We want to do isolated integration testing on the controller to confirm data flows as expected - and its similar on this controller to our other controllers utilizing MockBean for the service

**Pull request merged**
